export const projects = [
  {
    title: 'Paw Troopers',
    description: "A cute, challenging 2D tower defense game made using Unity. This project was my first major insight into using Jira for large-scale project management. I co-led 5+ years of development,  game and character design, testing, and a lot more.",
    image: '/images/1.png',
    tags: ['Unity', 'Jira', 'C#', 'Adobe Illustrator'],
    source: '',
    visit: 'https://pawtroopers.com/',
    id: 0,
  },
  {
    title: 'VisualPromptBuilder',
    description: "VisualPromptBuilder is my final year university project; a responsive web app designed to help nonverbal and cognitively disabled individuals communicate. It allows users to construct sentences using pictograms, which are then translated and vocalized in multiple languages.",
    image: '/images/8.png',
    tags: ['TypeScript', 'Next.js', 'Web Speech APIs', 'Translation APIs'],
    source: '',
    visit: 'https://youtu.be/8Ne-DSrmwEA',
    id: 1,
  },  
  {
    title: 'ImmunoFortress',
    description: "Collaborated with 3 colleagues to develop a multi-platform tower defense game using Unity and C#. I designed graphics using Adobe Illustrator and created a video presentation with Premiere Pro. The game is hosted on GitHub Pages and was part of a university project, where we achieved an 85% grade.",
    image: '/images/5.png',
    tags: ['Unity', 'C#', "Adobe Illustrator", "Premiere Pro"],
    source: '',
    visit: 'https://github.com/SPeedyZoZo/group-h-td',
    id: 2,
  },
  {
    title: 'LearnerLens',
    description: "Designed the prototype for AR glasses (LearnerLens) to enhance university lectures using Adobe Illustrator. I co-authored an intricate analysis study and report to document the impact of the product. The project showcased my skills in UX design and my ability to work on innovative solutions to improve educational experiences.",
    image: '/images/6.png',
    tags: ["Adobe Illustrator"],
    source: '',
    visit: 'https://www.behance.net/gallery/195585779/LearnerLens-QMUL-Project',
    id: 3,
  },
  {
    title: 'Trip Planning Weather App',
    description: "Developed and designed a weather app to help teachers plan school trips according to weather data as part of a group project in my university GUI module. I was responsible for designing all the UI elements and assisting in coding the frontend using Preact.",
    image: '/images/3.png',
    tags: ['Node.js', "Preact", 'JavaScript', 'HTML/CSS'],
    source: '',
    visit: 'https://github.com/SPeedyZoZo/Weather-App',
    id: 4,
  },
  {
    title: 'FDM Expense Management App',
    description: "Collaborated with 3 colleagues to develop a reimbursement and expense management app for FDM Group. I contributed to mainly designs and frontend development. This project provided experience in developing enterprise-level applications.",
    image: '/images/4.png',
    tags: ['React', 'Node.js', 'JavaScript', "Adobe Illustrator"],
    source: '',
    visit: 'https://github.com/SPeedyZoZo/FDM-App',
    id: 5,
  },
  {
    title: 'Image Processing App',
    description: "Developed a Java application for applying various image processing operations to one or more images. The project includes over ten operations, and helped me deepen my understanding of image processing techniques and Java programming.",
    image: '/images/7.png',
    tags: ['Java', 'AWT', 'Swing', 'Image Processing'],
    source: '',
    visit: 'https://github.com/SPeedyZoZo/image-processing-cw',
    id: 6,
  },
  {
    title: 'Spotify Web API Playlist Analyser',
    description: "Led a group of 4 to develop a research paper exploring the correlation between song attributes and network properties using the Spotify API. This project taught me data collection, analysis, and visualization using Pandas and NetworkX.",
    image: '/images/9.png',
    tags: ['Spotify API', 'Pandas', 'NetworkX'],
    source: '',
    visit: 'https://github.com/SPeedyZoZo/Spotify-API-Analysis',
    id: 7,
  },
];


export const TimeLineData = [
  { year: 2015, text: 'Enlightened myself to the world of coding through the Unity Game Development Engine', },
  { year: 2016, text: 'Hosted my own Game Dev Club in school teaching the basics to a group of around 30 people', },
  { year: 2017, text: 'Designed "upcoming tech" related presentations used for private meetups in NYUAD', },
  { year: 2018, text: 'Worked in a research centre to test a mobile application, using tools such as Jira', },
  { year: 2019, text: 'Began development on my full-scale game project using Unity', },
  { year: 2020, text: 'Volunteered to help with design and website work in WMUN', },
  { year: 2021, text: 'Worked as Director of Media and Graphic Design, increasing work load while managing a team of designers', },
  { year: 2022, text: 'Developed and worked on many projects which honed my passion and skillset for web development and UI/UX design', },
  { year: 2023, text: 'Completed more group and solo projects, solidifying my specialty in front-end design and development', },
  { year: 2024, text: 'Graduated University, prepared to enter the workforce... and whatever awaits beyond', },
  { year: 2025, text: 'More coming soon...' }
];